# tidb-lightning.toml
[lightning]
# Logs
level = "info"
file = "tidb-lightning.log"

[tikv-importer]
# "local" backend mode is chosen for better performance.
backend = "local"
# Temporary storage directory for the sorted Key-Value files.
sorted-kv-dir = "/Users/alo/OpenQ-ETL/tmp/sorted-kv-dir"

[mydumper]
# Data source directory
data-source-dir = "./csv/"

[tidb]
# TiDB server address
host = "127.0.0.1"
port = 4000
user = "root"
status-port = 10080
